language: cpp
compiler: gcc
sudo: true
install:
  - sudo apt-get install libgtest-dev -y
  - pushd /usr/src/gtest
  - sudo mkdir build
  - cd build
  - sudo cmake ../
  - sudo make
  - sudo make install
  - popd
script:
  - cmake CMakeLists.txt -DMATH_BUILD_TESTS=ON
  - make
  - ctest
