language: cpp
compiler: gcc

install:
  - wget https://github.com/google/googletest/archive/release-1.8.0.tar.gz
  - tar xf release-1.8.0.tar.gz
  - cd googletest-release-1.8.0
  - cmake -DBUILD_SHARED_LIBS=ON
  - make
script:
  - cmake CMakeLists.txt -DMATH_BUILD_TESTS=ON
  - make
  - ctest .
